framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"

        routing:
            'App\Music\Application\Message\UploadMusicMessage': async
            # Route your messages to the transports
            # 'App\Message\YourMessage': async

        default_bus: messenger.bus.commands

        buses:
            messenger.bus.commands:
                middleware:
                    - validation

            messenger.bus.queries:
                middleware:
                    - validation

            messenger.bus.cloud:
                middleware:
                    - validation