upload_music:
  path: /api/v1/music/upload
  controller: App\Music\Ui\Action\UploadMusicAction
  methods: [POST]

get_all_authors:
  path: /api/v1/music/author
  controller: App\Music\Ui\Action\GetAuthorsAction
  methods: [ GET ]

get_author:
  path: /api/v1/music/author/{authorId}
  controller: App\Music\Ui\Action\GetAuthorByIdAction
  methods: [GET]

get_album:
  path: /api/v1/music/album/{albumId}
  controller: App\Music\Ui\Action\GetAlbumByIdAction
  methods: [GET]

get_song:
  path: /api/v1/music/song/{id}
  controller: App\Music\Ui\Action\GetSongAction
  methods: [GET]

get_album_cover_image:
  path: /api/v1/music/album/{albumId}/cover
  controller: App\Music\Ui\Action\GetAlbumCoverByAlbumIdAction
  methods: [GET]

play_song:
  path: /api/v1/music/song/{songId}/play
  controller: App\Music\Ui\Action\PlaySongAction
  methods: [GET]

create_motorcycle:
  path: /api/v1/motorcycle
  controller: App\BasicExample\Ui\Action\CreateMotorcycleAction
  methods: [POST]

get_motorcycles:
  path: /api/v1/motorcycle
  controller: App\BasicExample\Ui\Action\GetMotorcyclesAction
  methods: [GET]

kafka_rest_get_messages:
  path: /api/v1/kafka-rest
  controller: App\BasicExample\Ui\Action\GetKafkaMessageFromRestAction
  methods: [GET]

kafka_rest_post_messages:
  path: /api/v1/kafka-rest
  controller: App\BasicExample\Ui\Action\ProduceKafkaMessageFromRestProxyAction
  methods: [POST]